#include <iostream>
#include <cstring>

#define BUF_SIZE 256
#define POKE_NUM 719

typedef struct Poke {
	char name[BUF_SIZE];
	char type[BUF_SIZE];
}Poke;

void insertData(Poke**);

int main() {
	Poke** arr;
	int num;

	arr = (Poke**)malloc(sizeof(Poke*) * POKE_NUM);

	for (int i = 0; i < POKE_NUM; ++i) {
		arr[i] = (Poke*)malloc(sizeof(Poke));
	}

	insertData(arr);

	scanf("%d", &num);
	printf("%s\n%s", arr[num]->name, arr[num]->type);

	for (int i = 0; i < POKE_NUM; ++i) {
		free(arr[i]);
	}

	free(arr);

	return 0;
}

void insertData(Poke** arr) {
	strcpy(arr[1]->name, "Bulbasaur");
	strcpy(arr[1]->type, "Grass Poison");
	strcpy(arr[2]->name, "Ivysaur");
	strcpy(arr[2]->type, "Grass Poison");
	strcpy(arr[3]->name, "Venusaur");
	strcpy(arr[3]->type, "Grass Poison");
	strcpy(arr[4]->name, "Charmander");
	strcpy(arr[4]->type, "Fire");
	strcpy(arr[5]->name, "Charmeleon");
	strcpy(arr[5]->type, "Fire");
	strcpy(arr[6]->name, "Charizard");
	strcpy(arr[6]->type, "Fire Flying");
	strcpy(arr[7]->name, "Squirtle");
	strcpy(arr[7]->type, "Water");
	strcpy(arr[8]->name, "Wartortle");
	strcpy(arr[8]->type, "Water");
	strcpy(arr[9]->name, "Blastoise");
	strcpy(arr[9]->type, "Water");
	strcpy(arr[10]->name, "Caterpie");
	strcpy(arr[10]->type, "Bug");
	strcpy(arr[11]->name, "Metapod");
	strcpy(arr[11]->type, "Bug");
	strcpy(arr[12]->name, "Butterfree");
	strcpy(arr[12]->type, "Bug Flying");
	strcpy(arr[13]->name, "Weedle");
	strcpy(arr[13]->type, "Bug Poison");
	strcpy(arr[14]->name, "Kakuna");
	strcpy(arr[14]->type, "Bug Poison");
	strcpy(arr[15]->name, "Beedrill");
	strcpy(arr[15]->type, "Bug Poison");
	strcpy(arr[16]->name, "Pidgey");
	strcpy(arr[16]->type, "Normal Flying");
	strcpy(arr[17]->name, "Pidgeotto");
	strcpy(arr[17]->type, "Normal Flying");
	strcpy(arr[18]->name, "Pidgeot");
	strcpy(arr[18]->type, "Normal Flying");
	strcpy(arr[19]->name, "Rattata");
	strcpy(arr[19]->type, "Normal");
	strcpy(arr[20]->name, "Raticate");
	strcpy(arr[20]->type, "Normal");
	strcpy(arr[21]->name, "Spearow");
	strcpy(arr[21]->type, "Normal Flying");
	strcpy(arr[22]->name, "Fearow");
	strcpy(arr[22]->type, "Normal Flying");
	strcpy(arr[23]->name, "Ekans");
	strcpy(arr[23]->type, "Poison");
	strcpy(arr[24]->name, "Arbok");
	strcpy(arr[24]->type, "Poison");
	strcpy(arr[25]->name, "Pikachu");
	strcpy(arr[25]->type, "Electric");
	strcpy(arr[26]->name, "Raichu");
	strcpy(arr[26]->type, "Electric");
	strcpy(arr[27]->name, "Sandshrew");
	strcpy(arr[27]->type, "Ground");
	strcpy(arr[28]->name, "Sandslash");
	strcpy(arr[28]->type, "Ground");
	strcpy(arr[29]->name, "Nidoran♀");
	strcpy(arr[29]->type, "Poison");
	strcpy(arr[30]->name, "Nidorina");
	strcpy(arr[30]->type, "Poison");
	strcpy(arr[31]->name, "Nidoqueen");
	strcpy(arr[31]->type, "Poison Ground");
	strcpy(arr[32]->name, "Nidoran♂");
	strcpy(arr[32]->type, "Poison");
	strcpy(arr[33]->name, "Nidorino");
	strcpy(arr[33]->type, "Poison");
	strcpy(arr[34]->name, "Nidoking");
	strcpy(arr[34]->type, "Poison Ground");
	strcpy(arr[35]->name, "Clefairy");
	strcpy(arr[35]->type, "Fairy");
	strcpy(arr[36]->name, "Clefable");
	strcpy(arr[36]->type, "Fairy");
	strcpy(arr[37]->name, "Vulpix");
	strcpy(arr[37]->type, "Fire");
	strcpy(arr[38]->name, "Ninetales");
	strcpy(arr[38]->type, "Fire");
	strcpy(arr[39]->name, "Jigglypuff");
	strcpy(arr[39]->type, "Normal Fairy");
	strcpy(arr[40]->name, "Wigglytuff");
	strcpy(arr[40]->type, "Normal Fairy");
	strcpy(arr[41]->name, "Zubat");
	strcpy(arr[41]->type, "Poison Flying");
	strcpy(arr[42]->name, "Golbat");
	strcpy(arr[42]->type, "Poison Flying");
	strcpy(arr[43]->name, "Oddish");
	strcpy(arr[43]->type, "Grass Poison");
	strcpy(arr[44]->name, "Gloom");
	strcpy(arr[44]->type, "Grass Poison");
	strcpy(arr[45]->name, "Vileplume");
	strcpy(arr[45]->type, "Grass Poison");
	strcpy(arr[46]->name, "Paras");
	strcpy(arr[46]->type, "Bug Grass");
	strcpy(arr[47]->name, "Parasect");
	strcpy(arr[47]->type, "Bug Grass");
	strcpy(arr[48]->name, "Venonat");
	strcpy(arr[48]->type, "Bug Poison");
	strcpy(arr[49]->name, "Venomoth");
	strcpy(arr[49]->type, "Bug Poison");
	strcpy(arr[50]->name, "Diglett");
	strcpy(arr[50]->type, "Ground");
	strcpy(arr[51]->name, "Dugtrio");
	strcpy(arr[51]->type, "Ground");
	strcpy(arr[52]->name, "Meowth");
	strcpy(arr[52]->type, "Normal");
	strcpy(arr[53]->name, "Persian");
	strcpy(arr[53]->type, "Normal");
	strcpy(arr[54]->name, "Psyduck");
	strcpy(arr[54]->type, "Water");
	strcpy(arr[55]->name, "Golduck");
	strcpy(arr[55]->type, "Water");
	strcpy(arr[56]->name, "Mankey");
	strcpy(arr[56]->type, "Fighting");
	strcpy(arr[57]->name, "Primeape");
	strcpy(arr[57]->type, "Fighting");
	strcpy(arr[58]->name, "Growlithe");
	strcpy(arr[58]->type, "Fire");
	strcpy(arr[59]->name, "Arcanine");
	strcpy(arr[59]->type, "Fire");
	strcpy(arr[60]->name, "Poliwag");
	strcpy(arr[60]->type, "Water");
	strcpy(arr[61]->name, "Poliwhirl");
	strcpy(arr[61]->type, "Water");
	strcpy(arr[62]->name, "Poliwrath");
	strcpy(arr[62]->type, "Water Fighting");
	strcpy(arr[63]->name, "Abra");
	strcpy(arr[63]->type, "Psychic");
	strcpy(arr[64]->name, "Kadabra");
	strcpy(arr[64]->type, "Psychic");
	strcpy(arr[65]->name, "Alakazam");
	strcpy(arr[65]->type, "Psychic");
	strcpy(arr[66]->name, "Machop");
	strcpy(arr[66]->type, "Fighting");
	strcpy(arr[67]->name, "Machoke");
	strcpy(arr[67]->type, "Fighting");
	strcpy(arr[68]->name, "Machamp");
	strcpy(arr[68]->type, "Fighting");
	strcpy(arr[69]->name, "Bellsprout");
	strcpy(arr[69]->type, "Grass Poison");
	strcpy(arr[70]->name, "Weepinbell");
	strcpy(arr[70]->type, "Grass Poison");
	strcpy(arr[71]->name, "Victreebel");
	strcpy(arr[71]->type, "Grass Poison");
	strcpy(arr[72]->name, "Tentacool");
	strcpy(arr[72]->type, "Water Poison");
	strcpy(arr[73]->name, "Tentacruel");
	strcpy(arr[73]->type, "Water Poison");
	strcpy(arr[74]->name, "Geodude");
	strcpy(arr[74]->type, "Rock Ground");
	strcpy(arr[75]->name, "Graveler");
	strcpy(arr[75]->type, "Rock Ground");
	strcpy(arr[76]->name, "Golem");
	strcpy(arr[76]->type, "Rock Ground");
	strcpy(arr[77]->name, "Ponyta");
	strcpy(arr[77]->type, "Fire");
	strcpy(arr[78]->name, "Rapidash");
	strcpy(arr[78]->type, "Fire");
	strcpy(arr[79]->name, "Slowpoke");
	strcpy(arr[79]->type, "Water Psychic");
	strcpy(arr[80]->name, "Slowbro");
	strcpy(arr[80]->type, "Water Psychic");
	strcpy(arr[81]->name, "Magnemite");
	strcpy(arr[81]->type, "Electric Steel");
	strcpy(arr[82]->name, "Magneton");
	strcpy(arr[82]->type, "Electric Steel");
	strcpy(arr[83]->name, "Farfetch'd");
	strcpy(arr[83]->type, "Normal Flying");
	strcpy(arr[84]->name, "Doduo");
	strcpy(arr[84]->type, "Normal Flying");
	strcpy(arr[85]->name, "Dodrio");
	strcpy(arr[85]->type, "Normal Flying");
	strcpy(arr[86]->name, "Seel");
	strcpy(arr[86]->type, "Water");
	strcpy(arr[87]->name, "Dewgong");
	strcpy(arr[87]->type, "Water Ice");
	strcpy(arr[88]->name, "Grimer");
	strcpy(arr[88]->type, "Poison");
	strcpy(arr[89]->name, "Muk");
	strcpy(arr[89]->type, "Poison");
	strcpy(arr[90]->name, "Shellder");
	strcpy(arr[90]->type, "Water");
	strcpy(arr[91]->name, "Cloyster");
	strcpy(arr[91]->type, "Water Ice");
	strcpy(arr[92]->name, "Gastly");
	strcpy(arr[92]->type, "Ghost Poison");
	strcpy(arr[93]->name, "Haunter");
	strcpy(arr[93]->type, "Ghost Poison");
	strcpy(arr[94]->name, "Gengar");
	strcpy(arr[94]->type, "Ghost Poison");
	strcpy(arr[95]->name, "Onix");
	strcpy(arr[95]->type, "Rock Ground");
	strcpy(arr[96]->name, "Drowzee");
	strcpy(arr[96]->type, "Psychic");
	strcpy(arr[97]->name, "Hypno");
	strcpy(arr[97]->type, "Psychic");
	strcpy(arr[98]->name, "Krabby");
	strcpy(arr[98]->type, "Water");
	strcpy(arr[99]->name, "Kingler");
	strcpy(arr[99]->type, "Water");
	strcpy(arr[100]->name, "Voltorb");
	strcpy(arr[100]->type, "Electric");
	strcpy(arr[101]->name, "Electrode");
	strcpy(arr[101]->type, "Electric");
	strcpy(arr[102]->name, "Exeggcute");
	strcpy(arr[102]->type, "Grass Psychic");
	strcpy(arr[103]->name, "Exeggutor");
	strcpy(arr[103]->type, "Grass Psychic");
	strcpy(arr[104]->name, "Cubone");
	strcpy(arr[104]->type, "Ground");
	strcpy(arr[105]->name, "Marowak");
	strcpy(arr[105]->type, "Ground");
	strcpy(arr[106]->name, "Hitmonlee");
	strcpy(arr[106]->type, "Fighting");
	strcpy(arr[107]->name, "Hitmonchan");
	strcpy(arr[107]->type, "Fighting");
	strcpy(arr[108]->name, "Lickitung");
	strcpy(arr[108]->type, "Normal");
	strcpy(arr[109]->name, "Koffing");
	strcpy(arr[109]->type, "Poison");
	strcpy(arr[110]->name, "Weezing");
	strcpy(arr[110]->type, "Poison");
	strcpy(arr[111]->name, "Rhyhorn");
	strcpy(arr[111]->type, "Ground Rock");
	strcpy(arr[112]->name, "Rhydon");
	strcpy(arr[112]->type, "Ground Rock");
	strcpy(arr[113]->name, "Chansey");
	strcpy(arr[113]->type, "Normal");
	strcpy(arr[114]->name, "Tangela");
	strcpy(arr[114]->type, "Grass");
	strcpy(arr[115]->name, "Kangaskhan");
	strcpy(arr[115]->type, "Normal");
	strcpy(arr[116]->name, "Horsea");
	strcpy(arr[116]->type, "Water");
	strcpy(arr[117]->name, "Seadra");
	strcpy(arr[117]->type, "Water");
	strcpy(arr[118]->name, "Goldeen");
	strcpy(arr[118]->type, "Water");
	strcpy(arr[119]->name, "Seaking");
	strcpy(arr[119]->type, "Water");
	strcpy(arr[120]->name, "Staryu");
	strcpy(arr[120]->type, "Water");
	strcpy(arr[121]->name, "Starmie");
	strcpy(arr[121]->type, "Water Psychic");
	strcpy(arr[122]->name, "Mr. Mime");
	strcpy(arr[122]->type, "Psychic Fairy");
	strcpy(arr[123]->name, "Scyther");
	strcpy(arr[123]->type, "Bug Flying");
	strcpy(arr[124]->name, "Jynx");
	strcpy(arr[124]->type, "Ice Psychic");
	strcpy(arr[125]->name, "Electabuzz");
	strcpy(arr[125]->type, "Electric");
	strcpy(arr[126]->name, "Magmar");
	strcpy(arr[126]->type, "Fire");
	strcpy(arr[127]->name, "Pinsir");
	strcpy(arr[127]->type, "Bug");
	strcpy(arr[128]->name, "Tauros");
	strcpy(arr[128]->type, "Normal");
	strcpy(arr[129]->name, "Magikarp");
	strcpy(arr[129]->type, "Water");
	strcpy(arr[130]->name, "Gyarados");
	strcpy(arr[130]->type, "Water Flying");
	strcpy(arr[131]->name, "Lapras");
	strcpy(arr[131]->type, "Water Ice");
	strcpy(arr[132]->name, "Ditto");
	strcpy(arr[132]->type, "Normal");
	strcpy(arr[133]->name, "Eevee");
	strcpy(arr[133]->type, "Normal");
	strcpy(arr[134]->name, "Vaporeon");
	strcpy(arr[134]->type, "Water");
	strcpy(arr[135]->name, "Jolteon");
	strcpy(arr[135]->type, "Electric");
	strcpy(arr[136]->name, "Flareon");
	strcpy(arr[136]->type, "Fire");
	strcpy(arr[137]->name, "Porygon");
	strcpy(arr[137]->type, "Normal");
	strcpy(arr[138]->name, "Omanyte");
	strcpy(arr[138]->type, "Rock Water");
	strcpy(arr[139]->name, "Omastar");
	strcpy(arr[139]->type, "Rock Water");
	strcpy(arr[140]->name, "Kabuto");
	strcpy(arr[140]->type, "Rock Water");
	strcpy(arr[141]->name, "Kabutops");
	strcpy(arr[141]->type, "Rock Water");
	strcpy(arr[142]->name, "Aerodactyl");
	strcpy(arr[142]->type, "Rock Flying");
	strcpy(arr[143]->name, "Snorlax");
	strcpy(arr[143]->type, "Normal");
	strcpy(arr[144]->name, "Articuno");
	strcpy(arr[144]->type, "Ice Flying");
	strcpy(arr[145]->name, "Zapdos");
	strcpy(arr[145]->type, "Electric Flying");
	strcpy(arr[146]->name, "Moltres");
	strcpy(arr[146]->type, "Fire Flying");
	strcpy(arr[147]->name, "Dratini");
	strcpy(arr[147]->type, "Dragon");
	strcpy(arr[148]->name, "Dragonair");
	strcpy(arr[148]->type, "Dragon");
	strcpy(arr[149]->name, "Dragonite");
	strcpy(arr[149]->type, "Dragon Flying");
	strcpy(arr[150]->name, "Mewtwo");
	strcpy(arr[150]->type, "Psychic");
	strcpy(arr[151]->name, "Mew");
	strcpy(arr[151]->type, "Psychic");
	strcpy(arr[152]->name, "Chikorita");
	strcpy(arr[152]->type, "Grass");
	strcpy(arr[153]->name, "Bayleef");
	strcpy(arr[153]->type, "Grass");
	strcpy(arr[154]->name, "Meganium");
	strcpy(arr[154]->type, "Grass");
	strcpy(arr[155]->name, "Cyndaquil");
	strcpy(arr[155]->type, "Fire");
	strcpy(arr[156]->name, "Quilava");
	strcpy(arr[156]->type, "Fire");
	strcpy(arr[157]->name, "Typhlosion");
	strcpy(arr[157]->type, "Fire");
	strcpy(arr[158]->name, "Totodile");
	strcpy(arr[158]->type, "Water");
	strcpy(arr[159]->name, "Croconaw");
	strcpy(arr[159]->type, "Water");
	strcpy(arr[160]->name, "Feraligatr");
	strcpy(arr[160]->type, "Water");
	strcpy(arr[161]->name, "Sentret");
	strcpy(arr[161]->type, "Normal");
	strcpy(arr[162]->name, "Furret");
	strcpy(arr[162]->type, "Normal");
	strcpy(arr[163]->name, "Hoothoot");
	strcpy(arr[163]->type, "Normal Flying");
	strcpy(arr[164]->name, "Noctowl");
	strcpy(arr[164]->type, "Normal Flying");
	strcpy(arr[165]->name, "Ledyba");
	strcpy(arr[165]->type, "Bug Flying");
	strcpy(arr[166]->name, "Ledian");
	strcpy(arr[166]->type, "Bug Flying");
	strcpy(arr[167]->name, "Spinarak");
	strcpy(arr[167]->type, "Bug Poison");
	strcpy(arr[168]->name, "Ariados");
	strcpy(arr[168]->type, "Bug Poison");
	strcpy(arr[169]->name, "Crobat");
	strcpy(arr[169]->type, "Poison Flying");
	strcpy(arr[170]->name, "Chinchou");
	strcpy(arr[170]->type, "Water Electric");
	strcpy(arr[171]->name, "Lanturn");
	strcpy(arr[171]->type, "Water Electric");
	strcpy(arr[172]->name, "Pichu");
	strcpy(arr[172]->type, "Electric");
	strcpy(arr[173]->name, "Cleffa");
	strcpy(arr[173]->type, "Fairy");
	strcpy(arr[174]->name, "Igglybuff");
	strcpy(arr[174]->type, "Normal Fairy");
	strcpy(arr[175]->name, "Togepi");
	strcpy(arr[175]->type, "Fairy");
	strcpy(arr[176]->name, "Togetic");
	strcpy(arr[176]->type, "Fairy Flying");
	strcpy(arr[177]->name, "Natu");
	strcpy(arr[177]->type, "Psychic Flying");
	strcpy(arr[178]->name, "Xatu");
	strcpy(arr[178]->type, "Psychic Flying");
	strcpy(arr[179]->name, "Mareep");
	strcpy(arr[179]->type, "Electric");
	strcpy(arr[180]->name, "Flaaffy");
	strcpy(arr[180]->type, "Electric");
	strcpy(arr[181]->name, "Ampharos");
	strcpy(arr[181]->type, "Electric");
	strcpy(arr[182]->name, "Bellossom");
	strcpy(arr[182]->type, "Grass");
	strcpy(arr[183]->name, "Marill");
	strcpy(arr[183]->type, "Water Fairy");
	strcpy(arr[184]->name, "Azumarill");
	strcpy(arr[184]->type, "Water Fairy");
	strcpy(arr[185]->name, "Sudowoodo");
	strcpy(arr[185]->type, "Rock");
	strcpy(arr[186]->name, "Politoed");
	strcpy(arr[186]->type, "Water");
	strcpy(arr[187]->name, "Hoppip");
	strcpy(arr[187]->type, "Grass Flying");
	strcpy(arr[188]->name, "Skiploom");
	strcpy(arr[188]->type, "Grass Flying");
	strcpy(arr[189]->name, "Jumpluff");
	strcpy(arr[189]->type, "Grass Flying");
	strcpy(arr[190]->name, "Aipom");
	strcpy(arr[190]->type, "Normal");
	strcpy(arr[191]->name, "Sunkern");
	strcpy(arr[191]->type, "Grass");
	strcpy(arr[192]->name, "Sunflora");
	strcpy(arr[192]->type, "Grass");
	strcpy(arr[193]->name, "Yanma");
	strcpy(arr[193]->type, "Bug Flying");
	strcpy(arr[194]->name, "Wooper");
	strcpy(arr[194]->type, "Water Ground");
	strcpy(arr[195]->name, "Quagsire");
	strcpy(arr[195]->type, "Water Ground");
	strcpy(arr[196]->name, "Espeon");
	strcpy(arr[196]->type, "Psychic");
	strcpy(arr[197]->name, "Umbreon");
	strcpy(arr[197]->type, "Dark");
	strcpy(arr[198]->name, "Murkrow");
	strcpy(arr[198]->type, "Dark Flying");
	strcpy(arr[199]->name, "Slowking");
	strcpy(arr[199]->type, "Water Psychic");
	strcpy(arr[200]->name, "Misdreavus");
	strcpy(arr[200]->type, "Ghost");
	strcpy(arr[201]->name, "Unown");
	strcpy(arr[201]->type, "Psychic");
	strcpy(arr[202]->name, "Wobbuffet");
	strcpy(arr[202]->type, "Psychic");
	strcpy(arr[203]->name, "Girafarig");
	strcpy(arr[203]->type, "Normal Psychic");
	strcpy(arr[204]->name, "Pineco");
	strcpy(arr[204]->type, "Bug");
	strcpy(arr[205]->name, "Forretress");
	strcpy(arr[205]->type, "Bug Steel");
	strcpy(arr[206]->name, "Dunsparce");
	strcpy(arr[206]->type, "Normal");
	strcpy(arr[207]->name, "Gligar");
	strcpy(arr[207]->type, "Ground Flying");
	strcpy(arr[208]->name, "Steelix");
	strcpy(arr[208]->type, "Steel Ground");
	strcpy(arr[209]->name, "Snubbull");
	strcpy(arr[209]->type, "Fairy");
	strcpy(arr[210]->name, "Granbull");
	strcpy(arr[210]->type, "Fairy");
	strcpy(arr[211]->name, "Qwilfish");
	strcpy(arr[211]->type, "Water Poison");
	strcpy(arr[212]->name, "Scizor");
	strcpy(arr[212]->type, "Bug Steel");
	strcpy(arr[213]->name, "Shuckle");
	strcpy(arr[213]->type, "Bug Rock");
	strcpy(arr[214]->name, "Heracross");
	strcpy(arr[214]->type, "Bug Fighting");
	strcpy(arr[215]->name, "Sneasel");
	strcpy(arr[215]->type, "Dark Ice");
	strcpy(arr[216]->name, "Teddiursa");
	strcpy(arr[216]->type, "Normal");
	strcpy(arr[217]->name, "Ursaring");
	strcpy(arr[217]->type, "Normal");
	strcpy(arr[218]->name, "Slugma");
	strcpy(arr[218]->type, "Fire");
	strcpy(arr[219]->name, "Magcargo");
	strcpy(arr[219]->type, "Fire Rock");
	strcpy(arr[220]->name, "Swinub");
	strcpy(arr[220]->type, "Ice Ground");
	strcpy(arr[221]->name, "Piloswine");
	strcpy(arr[221]->type, "Ice Ground");
	strcpy(arr[222]->name, "Corsola");
	strcpy(arr[222]->type, "Water Rock");
	strcpy(arr[223]->name, "Remoraid");
	strcpy(arr[223]->type, "Water");
	strcpy(arr[224]->name, "Octillery");
	strcpy(arr[224]->type, "Water");
	strcpy(arr[225]->name, "Delibird");
	strcpy(arr[225]->type, "Ice Flying");
	strcpy(arr[226]->name, "Mantine");
	strcpy(arr[226]->type, "Water Flying");
	strcpy(arr[227]->name, "Skarmory");
	strcpy(arr[227]->type, "Steel Flying");
	strcpy(arr[228]->name, "Houndour");
	strcpy(arr[228]->type, "Dark Fire");
	strcpy(arr[229]->name, "Houndoom");
	strcpy(arr[229]->type, "Dark Fire");
	strcpy(arr[230]->name, "Kingdra");
	strcpy(arr[230]->type, "Water Dragon");
	strcpy(arr[231]->name, "Phanpy");
	strcpy(arr[231]->type, "Ground");
	strcpy(arr[232]->name, "Donphan");
	strcpy(arr[232]->type, "Ground");
	strcpy(arr[233]->name, "Porygon2");
	strcpy(arr[233]->type, "Normal");
	strcpy(arr[234]->name, "Stantler");
	strcpy(arr[234]->type, "Normal");
	strcpy(arr[235]->name, "Smeargle");
	strcpy(arr[235]->type, "Normal");
	strcpy(arr[236]->name, "Tyrogue");
	strcpy(arr[236]->type, "Fighting");
	strcpy(arr[237]->name, "Hitmontop");
	strcpy(arr[237]->type, "Fighting");
	strcpy(arr[238]->name, "Smoochum");
	strcpy(arr[238]->type, "Ice Psychic");
	strcpy(arr[239]->name, "Elekid");
	strcpy(arr[239]->type, "Electric");
	strcpy(arr[240]->name, "Magby");
	strcpy(arr[240]->type, "Fire");
	strcpy(arr[241]->name, "Miltank");
	strcpy(arr[241]->type, "Normal");
	strcpy(arr[242]->name, "Blissey");
	strcpy(arr[242]->type, "Normal");
	strcpy(arr[243]->name, "Raikou");
	strcpy(arr[243]->type, "Electric");
	strcpy(arr[244]->name, "Entei");
	strcpy(arr[244]->type, "Fire");
	strcpy(arr[245]->name, "Suicune");
	strcpy(arr[245]->type, "Water");
	strcpy(arr[246]->name, "Larvitar");
	strcpy(arr[246]->type, "Rock Ground");
	strcpy(arr[247]->name, "Pupitar");
	strcpy(arr[247]->type, "Rock Ground");
	strcpy(arr[248]->name, "Tyranitar");
	strcpy(arr[248]->type, "Rock Dark");
	strcpy(arr[249]->name, "Lugia");
	strcpy(arr[249]->type, "Psychic Flying");
	strcpy(arr[250]->name, "Ho-oh");
	strcpy(arr[250]->type, "Fire Flying");
	strcpy(arr[251]->name, "Celebi");
	strcpy(arr[251]->type, "Psychic Grass");
	strcpy(arr[252]->name, "Treecko");
	strcpy(arr[252]->type, "Grass");
	strcpy(arr[253]->name, "Grovyle");
	strcpy(arr[253]->type, "Grass");
	strcpy(arr[254]->name, "Sceptile");
	strcpy(arr[254]->type, "Grass");
	strcpy(arr[255]->name, "Torchic");
	strcpy(arr[255]->type, "Fire");
	strcpy(arr[256]->name, "Combusken");
	strcpy(arr[256]->type, "Fire Fighting");
	strcpy(arr[257]->name, "Blaziken");
	strcpy(arr[257]->type, "Fire Fighting");
	strcpy(arr[258]->name, "Mudkip");
	strcpy(arr[258]->type, "Water");
	strcpy(arr[259]->name, "Marshtomp");
	strcpy(arr[259]->type, "Water Ground");
	strcpy(arr[260]->name, "Swampert");
	strcpy(arr[260]->type, "Water Ground");
	strcpy(arr[261]->name, "Poochyena");
	strcpy(arr[261]->type, "Dark");
	strcpy(arr[262]->name, "Mightyena");
	strcpy(arr[262]->type, "Dark");
	strcpy(arr[263]->name, "Zigzagoon");
	strcpy(arr[263]->type, "Normal");
	strcpy(arr[264]->name, "Linoone");
	strcpy(arr[264]->type, "Normal");
	strcpy(arr[265]->name, "Wurmple");
	strcpy(arr[265]->type, "Bug");
	strcpy(arr[266]->name, "Silcoon");
	strcpy(arr[266]->type, "Bug");
	strcpy(arr[267]->name, "Beautifly");
	strcpy(arr[267]->type, "Bug Flying");
	strcpy(arr[268]->name, "Cascoon");
	strcpy(arr[268]->type, "Bug");
	strcpy(arr[269]->name, "Dustox");
	strcpy(arr[269]->type, "Bug Poison");
	strcpy(arr[270]->name, "Lotad");
	strcpy(arr[270]->type, "Water Grass");
	strcpy(arr[271]->name, "Lombre");
	strcpy(arr[271]->type, "Water Grass");
	strcpy(arr[272]->name, "Ludicolo");
	strcpy(arr[272]->type, "Water Grass");
	strcpy(arr[273]->name, "Seedot");
	strcpy(arr[273]->type, "Grass");
	strcpy(arr[274]->name, "Nuzleaf");
	strcpy(arr[274]->type, "Grass Dark");
	strcpy(arr[275]->name, "Shiftry");
	strcpy(arr[275]->type, "Grass Dark");
	strcpy(arr[276]->name, "Taillow");
	strcpy(arr[276]->type, "Normal Flying");
	strcpy(arr[277]->name, "Swellow");
	strcpy(arr[277]->type, "Normal Flying");
	strcpy(arr[278]->name, "Wingull");
	strcpy(arr[278]->type, "Water Flying");
	strcpy(arr[279]->name, "Pelipper");
	strcpy(arr[279]->type, "Water Flying");
	strcpy(arr[280]->name, "Ralts");
	strcpy(arr[280]->type, "Psychic Fairy");
	strcpy(arr[281]->name, "Kirlia");
	strcpy(arr[281]->type, "Psychic Fairy");
	strcpy(arr[282]->name, "Gardevoir");
	strcpy(arr[282]->type, "Psychic Fairy");
	strcpy(arr[283]->name, "Surskit");
	strcpy(arr[283]->type, "Bug Water");
	strcpy(arr[284]->name, "Masquerain");
	strcpy(arr[284]->type, "Bug Flying");
	strcpy(arr[285]->name, "Shroomish");
	strcpy(arr[285]->type, "Grass");
	strcpy(arr[286]->name, "Breloom");
	strcpy(arr[286]->type, "Grass Fighting");
	strcpy(arr[287]->name, "Slakoth");
	strcpy(arr[287]->type, "Normal");
	strcpy(arr[288]->name, "Vigoroth");
	strcpy(arr[288]->type, "Normal");
	strcpy(arr[289]->name, "Slaking");
	strcpy(arr[289]->type, "Normal");
	strcpy(arr[290]->name, "Nincada");
	strcpy(arr[290]->type, "Bug Ground");
	strcpy(arr[291]->name, "Ninjask");
	strcpy(arr[291]->type, "Bug Flying");
	strcpy(arr[292]->name, "Shedinja");
	strcpy(arr[292]->type, "Bug Ghost");
	strcpy(arr[293]->name, "Whismur");
	strcpy(arr[293]->type, "Normal");
	strcpy(arr[294]->name, "Loudred");
	strcpy(arr[294]->type, "Normal");
	strcpy(arr[295]->name, "Exploud");
	strcpy(arr[295]->type, "Normal");
	strcpy(arr[296]->name, "Makuhita");
	strcpy(arr[296]->type, "Fighting");
	strcpy(arr[297]->name, "Hariyama");
	strcpy(arr[297]->type, "Fighting");
	strcpy(arr[298]->name, "Azurill");
	strcpy(arr[298]->type, "Normal Fairy");
	strcpy(arr[299]->name, "Nosepass");
	strcpy(arr[299]->type, "Rock");
	strcpy(arr[300]->name, "Skitty");
	strcpy(arr[300]->type, "Normal");
	strcpy(arr[301]->name, "Delcatty");
	strcpy(arr[301]->type, "Normal");
	strcpy(arr[302]->name, "Sableye");
	strcpy(arr[302]->type, "Dark Ghost");
	strcpy(arr[303]->name, "Mawile");
	strcpy(arr[303]->type, "Steel Fairy");
	strcpy(arr[304]->name, "Aron");
	strcpy(arr[304]->type, "Steel Rock");
	strcpy(arr[305]->name, "Lairon");
	strcpy(arr[305]->type, "Steel Rock");
	strcpy(arr[306]->name, "Aggron");
	strcpy(arr[306]->type, "Steel Rock");
	strcpy(arr[307]->name, "Meditite");
	strcpy(arr[307]->type, "Fighting Psychic");
	strcpy(arr[308]->name, "Medicham");
	strcpy(arr[308]->type, "Fighting Psychic");
	strcpy(arr[309]->name, "Electrike");
	strcpy(arr[309]->type, "Electric");
	strcpy(arr[310]->name, "Manectric");
	strcpy(arr[310]->type, "Electric");
	strcpy(arr[311]->name, "Plusle");
	strcpy(arr[311]->type, "Electric");
	strcpy(arr[312]->name, "Minun");
	strcpy(arr[312]->type, "Electric");
	strcpy(arr[313]->name, "Volbeat");
	strcpy(arr[313]->type, "Bug");
	strcpy(arr[314]->name, "Illumise");
	strcpy(arr[314]->type, "Bug");
	strcpy(arr[315]->name, "Roselia");
	strcpy(arr[315]->type, "Grass Poison");
	strcpy(arr[316]->name, "Gulpin");
	strcpy(arr[316]->type, "Poison");
	strcpy(arr[317]->name, "Swalot");
	strcpy(arr[317]->type, "Poison");
	strcpy(arr[318]->name, "Carvanha");
	strcpy(arr[318]->type, "Water Dark");
	strcpy(arr[319]->name, "Sharpedo");
	strcpy(arr[319]->type, "Water Dark");
	strcpy(arr[320]->name, "Wailmer");
	strcpy(arr[320]->type, "Water");
	strcpy(arr[321]->name, "Wailord");
	strcpy(arr[321]->type, "Water");
	strcpy(arr[322]->name, "Numel");
	strcpy(arr[322]->type, "Fire Ground");
	strcpy(arr[323]->name, "Camerupt");
	strcpy(arr[323]->type, "Fire Ground");
	strcpy(arr[324]->name, "Torkoal");
	strcpy(arr[324]->type, "Fire");
	strcpy(arr[325]->name, "Spoink");
	strcpy(arr[325]->type, "Psychic");
	strcpy(arr[326]->name, "Grumpig");
	strcpy(arr[326]->type, "Psychic");
	strcpy(arr[327]->name, "Spinda");
	strcpy(arr[327]->type, "Normal");
	strcpy(arr[328]->name, "Trapinch");
	strcpy(arr[328]->type, "Ground");
	strcpy(arr[329]->name, "Vibrava");
	strcpy(arr[329]->type, "Ground Dragon");
	strcpy(arr[330]->name, "Flygon");
	strcpy(arr[330]->type, "Ground Dragon");
	strcpy(arr[331]->name, "Cacnea");
	strcpy(arr[331]->type, "Grass");
	strcpy(arr[332]->name, "Cacturne");
	strcpy(arr[332]->type, "Grass Dark");
	strcpy(arr[333]->name, "Swablu");
	strcpy(arr[333]->type, "Normal Flying");
	strcpy(arr[334]->name, "Altaria");
	strcpy(arr[334]->type, "Dragon Flying");
	strcpy(arr[335]->name, "Zangoose");
	strcpy(arr[335]->type, "Normal");
	strcpy(arr[336]->name, "Seviper");
	strcpy(arr[336]->type, "Poison");
	strcpy(arr[337]->name, "Lunatone");
	strcpy(arr[337]->type, "Rock Psychic");
	strcpy(arr[338]->name, "Solrock");
	strcpy(arr[338]->type, "Rock Psychic");
	strcpy(arr[339]->name, "Barboach");
	strcpy(arr[339]->type, "Water Ground");
	strcpy(arr[340]->name, "Whiscash");
	strcpy(arr[340]->type, "Water Ground");
	strcpy(arr[341]->name, "Corphish");
	strcpy(arr[341]->type, "Water");
	strcpy(arr[342]->name, "Crawdaunt");
	strcpy(arr[342]->type, "Water Dark");
	strcpy(arr[343]->name, "Baltoy");
	strcpy(arr[343]->type, "Ground Psychic");
	strcpy(arr[344]->name, "Claydol");
	strcpy(arr[344]->type, "Ground Psychic");
	strcpy(arr[345]->name, "Lileep");
	strcpy(arr[345]->type, "Rock Grass");
	strcpy(arr[346]->name, "Cradily");
	strcpy(arr[346]->type, "Rock Grass");
	strcpy(arr[347]->name, "Anorith");
	strcpy(arr[347]->type, "Rock Bug");
	strcpy(arr[348]->name, "Armaldo");
	strcpy(arr[348]->type, "Rock Bug");
	strcpy(arr[349]->name, "Feebas");
	strcpy(arr[349]->type, "Water");
	strcpy(arr[350]->name, "Milotic");
	strcpy(arr[350]->type, "Water");
	strcpy(arr[351]->name, "Castform");
	strcpy(arr[351]->type, "Normal");
	strcpy(arr[352]->name, "Kecleon");
	strcpy(arr[352]->type, "Normal");
	strcpy(arr[353]->name, "Shuppet");
	strcpy(arr[353]->type, "Ghost");
	strcpy(arr[354]->name, "Banette");
	strcpy(arr[354]->type, "Ghost");
	strcpy(arr[355]->name, "Duskull");
	strcpy(arr[355]->type, "Ghost");
	strcpy(arr[356]->name, "Dusclops");
	strcpy(arr[356]->type, "Ghost");
	strcpy(arr[357]->name, "Tropius");
	strcpy(arr[357]->type, "Grass Flying");
	strcpy(arr[358]->name, "Chimecho");
	strcpy(arr[358]->type, "Psychic");
	strcpy(arr[359]->name, "Absol");
	strcpy(arr[359]->type, "Dark");
	strcpy(arr[360]->name, "Wynaut");
	strcpy(arr[360]->type, "Psychic");
	strcpy(arr[361]->name, "Snorunt");
	strcpy(arr[361]->type, "Ice");
	strcpy(arr[362]->name, "Glalie");
	strcpy(arr[362]->type, "Ice");
	strcpy(arr[363]->name, "Spheal");
	strcpy(arr[363]->type, "Ice Water");
	strcpy(arr[364]->name, "Sealeo");
	strcpy(arr[364]->type, "Ice Water");
	strcpy(arr[365]->name, "Walrein");
	strcpy(arr[365]->type, "Ice Water");
	strcpy(arr[366]->name, "Clamperl");
	strcpy(arr[366]->type, "Water");
	strcpy(arr[367]->name, "Huntail");
	strcpy(arr[367]->type, "Water");
	strcpy(arr[368]->name, "Gorebyss");
	strcpy(arr[368]->type, "Water");
	strcpy(arr[369]->name, "Relicanth");
	strcpy(arr[369]->type, "Water Rock");
	strcpy(arr[370]->name, "Luvdisc");
	strcpy(arr[370]->type, "Water");
	strcpy(arr[371]->name, "Bagon");
	strcpy(arr[371]->type, "Dragon");
	strcpy(arr[372]->name, "Shelgon");
	strcpy(arr[372]->type, "Dragon");
	strcpy(arr[373]->name, "Salamence");
	strcpy(arr[373]->type, "Dragon Flying");
	strcpy(arr[374]->name, "Beldum");
	strcpy(arr[374]->type, "Steel Psychic");
	strcpy(arr[375]->name, "Metang");
	strcpy(arr[375]->type, "Steel Psychic");
	strcpy(arr[376]->name, "Metagross");
	strcpy(arr[376]->type, "Steel Psychic");
	strcpy(arr[377]->name, "Regirock");
	strcpy(arr[377]->type, "Rock");
	strcpy(arr[378]->name, "Regice");
	strcpy(arr[378]->type, "Ice");
	strcpy(arr[379]->name, "Registeel");
	strcpy(arr[379]->type, "Steel");
	strcpy(arr[380]->name, "Latias");
	strcpy(arr[380]->type, "Dragon Psychic");
	strcpy(arr[381]->name, "Latios");
	strcpy(arr[381]->type, "Dragon Psychic");
	strcpy(arr[382]->name, "Kyogre");
	strcpy(arr[382]->type, "Water");
	strcpy(arr[383]->name, "Groudon");
	strcpy(arr[383]->type, "Ground");
	strcpy(arr[384]->name, "Rayquaza");
	strcpy(arr[384]->type, "Dragon Flying");
	strcpy(arr[385]->name, "Jirachi");
	strcpy(arr[385]->type, "Steel Psychic");
	strcpy(arr[386]->name, "Deoxys");
	strcpy(arr[386]->type, "Psychic");
	strcpy(arr[387]->name, "Turtwig");
	strcpy(arr[387]->type, "Grass");
	strcpy(arr[388]->name, "Grotle");
	strcpy(arr[388]->type, "Grass");
	strcpy(arr[389]->name, "Torterra");
	strcpy(arr[389]->type, "Grass Ground");
	strcpy(arr[390]->name, "Chimchar");
	strcpy(arr[390]->type, "Fire");
	strcpy(arr[391]->name, "Monferno");
	strcpy(arr[391]->type, "Fire Fighting");
	strcpy(arr[392]->name, "Infernape");
	strcpy(arr[392]->type, "Fire Fighting");
	strcpy(arr[393]->name, "Piplup");
	strcpy(arr[393]->type, "Water");
	strcpy(arr[394]->name, "Prinplup");
	strcpy(arr[394]->type, "Water");
	strcpy(arr[395]->name, "Empoleon");
	strcpy(arr[395]->type, "Water Steel");
	strcpy(arr[396]->name, "Starly");
	strcpy(arr[396]->type, "Normal Flying");
	strcpy(arr[397]->name, "Staravia");
	strcpy(arr[397]->type, "Normal Flying");
	strcpy(arr[398]->name, "Staraptor");
	strcpy(arr[398]->type, "Normal Flying");
	strcpy(arr[399]->name, "Bidoof");
	strcpy(arr[399]->type, "Normal");
	strcpy(arr[400]->name, "Bibarel");
	strcpy(arr[400]->type, "Normal Water");
	strcpy(arr[401]->name, "Kricketot");
	strcpy(arr[401]->type, "Bug");
	strcpy(arr[402]->name, "Kricketune");
	strcpy(arr[402]->type, "Bug");
	strcpy(arr[403]->name, "Shinx");
	strcpy(arr[403]->type, "Electric");
	strcpy(arr[404]->name, "Luxio");
	strcpy(arr[404]->type, "Electric");
	strcpy(arr[405]->name, "Luxray");
	strcpy(arr[405]->type, "Electric");
	strcpy(arr[406]->name, "Budew");
	strcpy(arr[406]->type, "Grass Poison");
	strcpy(arr[407]->name, "Roserade");
	strcpy(arr[407]->type, "Grass Poison");
	strcpy(arr[408]->name, "Cranidos");
	strcpy(arr[408]->type, "Rock");
	strcpy(arr[409]->name, "Rampardos");
	strcpy(arr[409]->type, "Rock");
	strcpy(arr[410]->name, "Shieldon");
	strcpy(arr[410]->type, "Rock Steel");
	strcpy(arr[411]->name, "Bastiodon");
	strcpy(arr[411]->type, "Rock Steel");
	strcpy(arr[412]->name, "Burmy");
	strcpy(arr[412]->type, "Bug");
	strcpy(arr[413]->name, "Wormadam");
	strcpy(arr[413]->type, "Bug Grass");
	strcpy(arr[414]->name, "Mothim");
	strcpy(arr[414]->type, "Bug Flying");
	strcpy(arr[415]->name, "Combee");
	strcpy(arr[415]->type, "Bug Flying");
	strcpy(arr[416]->name, "Vespiquen");
	strcpy(arr[416]->type, "Bug Flying");
	strcpy(arr[417]->name, "Pachirisu");
	strcpy(arr[417]->type, "Electric");
	strcpy(arr[418]->name, "Buizel");
	strcpy(arr[418]->type, "Water");
	strcpy(arr[419]->name, "Floatzel");
	strcpy(arr[419]->type, "Water");
	strcpy(arr[420]->name, "Cherubi");
	strcpy(arr[420]->type, "Grass");
	strcpy(arr[421]->name, "Cherrim");
	strcpy(arr[421]->type, "Grass");
	strcpy(arr[422]->name, "Shellos");
	strcpy(arr[422]->type, "Water");
	strcpy(arr[423]->name, "Gastrodon");
	strcpy(arr[423]->type, "Water Ground");
	strcpy(arr[424]->name, "Ambipom");
	strcpy(arr[424]->type, "Normal");
	strcpy(arr[425]->name, "Drifloon");
	strcpy(arr[425]->type, "Ghost Flying");
	strcpy(arr[426]->name, "Drifblim");
	strcpy(arr[426]->type, "Ghost Flying");
	strcpy(arr[427]->name, "Buneary");
	strcpy(arr[427]->type, "Normal");
	strcpy(arr[428]->name, "Lopunny");
	strcpy(arr[428]->type, "Normal");
	strcpy(arr[429]->name, "Mismagius");
	strcpy(arr[429]->type, "Ghost");
	strcpy(arr[430]->name, "Honchkrow");
	strcpy(arr[430]->type, "Dark Flying");
	strcpy(arr[431]->name, "Glameow");
	strcpy(arr[431]->type, "Normal");
	strcpy(arr[432]->name, "Purugly");
	strcpy(arr[432]->type, "Normal");
	strcpy(arr[433]->name, "Chingling");
	strcpy(arr[433]->type, "Psychic");
	strcpy(arr[434]->name, "Stunky");
	strcpy(arr[434]->type, "Poison Dark");
	strcpy(arr[435]->name, "Skuntank");
	strcpy(arr[435]->type, "Poison Dark");
	strcpy(arr[436]->name, "Bronzor");
	strcpy(arr[436]->type, "Steel Psychic");
	strcpy(arr[437]->name, "Bronzong");
	strcpy(arr[437]->type, "Steel Psychic");
	strcpy(arr[438]->name, "Bonsly");
	strcpy(arr[438]->type, "Rock");
	strcpy(arr[439]->name, "Mime Jr.");
	strcpy(arr[439]->type, "Psychic Fairy");
	strcpy(arr[440]->name, "Happiny");
	strcpy(arr[440]->type, "Normal");
	strcpy(arr[441]->name, "Chatot");
	strcpy(arr[441]->type, "Normal Flying");
	strcpy(arr[442]->name, "Spiritomb");
	strcpy(arr[442]->type, "Ghost Dark");
	strcpy(arr[443]->name, "Gible");
	strcpy(arr[443]->type, "Dragon Ground");
	strcpy(arr[444]->name, "Gabite");
	strcpy(arr[444]->type, "Dragon Ground");
	strcpy(arr[445]->name, "Garchomp");
	strcpy(arr[445]->type, "Dragon Ground");
	strcpy(arr[446]->name, "Munchlax");
	strcpy(arr[446]->type, "Normal");
	strcpy(arr[447]->name, "Riolu");
	strcpy(arr[447]->type, "Fighting");
	strcpy(arr[448]->name, "Lucario");
	strcpy(arr[448]->type, "Fighting Steel");
	strcpy(arr[449]->name, "Hippopotas");
	strcpy(arr[449]->type, "Ground");
	strcpy(arr[450]->name, "Hippowdon");
	strcpy(arr[450]->type, "Ground");
	strcpy(arr[451]->name, "Skorupi");
	strcpy(arr[451]->type, "Poison Bug");
	strcpy(arr[452]->name, "Drapion");
	strcpy(arr[452]->type, "Poison Dark");
	strcpy(arr[453]->name, "Croagunk");
	strcpy(arr[453]->type, "Poison Fighting");
	strcpy(arr[454]->name, "Toxicroak");
	strcpy(arr[454]->type, "Poison Fighting");
	strcpy(arr[455]->name, "Carnivine");
	strcpy(arr[455]->type, "Grass");
	strcpy(arr[456]->name, "Finneon");
	strcpy(arr[456]->type, "Water");
	strcpy(arr[457]->name, "Lumineon");
	strcpy(arr[457]->type, "Water");
	strcpy(arr[458]->name, "Mantyke");
	strcpy(arr[458]->type, "Water Flying");
	strcpy(arr[459]->name, "Snover");
	strcpy(arr[459]->type, "Grass Ice");
	strcpy(arr[460]->name, "Abomasnow");
	strcpy(arr[460]->type, "Grass Ice");
	strcpy(arr[461]->name, "Weavile");
	strcpy(arr[461]->type, "Dark Ice");
	strcpy(arr[462]->name, "Magnezone");
	strcpy(arr[462]->type, "Electric Steel");
	strcpy(arr[463]->name, "Lickilicky");
	strcpy(arr[463]->type, "Normal");
	strcpy(arr[464]->name, "Rhyperior");
	strcpy(arr[464]->type, "Ground Rock");
	strcpy(arr[465]->name, "Tangrowth");
	strcpy(arr[465]->type, "Grass");
	strcpy(arr[466]->name, "Electivire");
	strcpy(arr[466]->type, "Electric");
	strcpy(arr[467]->name, "Magmortar");
	strcpy(arr[467]->type, "Fire");
	strcpy(arr[468]->name, "Togekiss");
	strcpy(arr[468]->type, "Fairy Flying");
	strcpy(arr[469]->name, "Yanmega");
	strcpy(arr[469]->type, "Bug Flying");
	strcpy(arr[470]->name, "Leafeon");
	strcpy(arr[470]->type, "Grass");
	strcpy(arr[471]->name, "Glaceon");
	strcpy(arr[471]->type, "Ice");
	strcpy(arr[472]->name, "Gliscor");
	strcpy(arr[472]->type, "Ground Flying");
	strcpy(arr[473]->name, "Mamoswine");
	strcpy(arr[473]->type, "Ice Ground");
	strcpy(arr[474]->name, "Porygon-Z");
	strcpy(arr[474]->type, "Normal");
	strcpy(arr[475]->name, "Gallade");
	strcpy(arr[475]->type, "Psychic Fighting");
	strcpy(arr[476]->name, "Probopass");
	strcpy(arr[476]->type, "Rock Steel");
	strcpy(arr[477]->name, "Dusknoir");
	strcpy(arr[477]->type, "Ghost");
	strcpy(arr[478]->name, "Froslass");
	strcpy(arr[478]->type, "Ice Ghost");
	strcpy(arr[479]->name, "Rotom");
	strcpy(arr[479]->type, "Electric Ghost");
	strcpy(arr[480]->name, "Uxie");
	strcpy(arr[480]->type, "Psychic");
	strcpy(arr[481]->name, "Mesprit");
	strcpy(arr[481]->type, "Psychic");
	strcpy(arr[482]->name, "Azelf");
	strcpy(arr[482]->type, "Psychic");
	strcpy(arr[483]->name, "Dialga");
	strcpy(arr[483]->type, "Steel Dragon");
	strcpy(arr[484]->name, "Palkia");
	strcpy(arr[484]->type, "Water Dragon");
	strcpy(arr[485]->name, "Heatran");
	strcpy(arr[485]->type, "Fire Steel");
	strcpy(arr[486]->name, "Regigigas");
	strcpy(arr[486]->type, "Normal");
	strcpy(arr[487]->name, "Giratina");
	strcpy(arr[487]->type, "Ghost Dragon");
	strcpy(arr[488]->name, "Cresselia");
	strcpy(arr[488]->type, "Psychic");
	strcpy(arr[489]->name, "Phione");
	strcpy(arr[489]->type, "Water");
	strcpy(arr[490]->name, "Manaphy");
	strcpy(arr[490]->type, "Water");
	strcpy(arr[491]->name, "Darkrai");
	strcpy(arr[491]->type, "Dark");
	strcpy(arr[492]->name, "Shaymin");
	strcpy(arr[492]->type, "Grass");
	strcpy(arr[493]->name, "Arceus");
	strcpy(arr[493]->type, "Normal");
	strcpy(arr[494]->name, "Victini");
	strcpy(arr[494]->type, "Psychic Fire");
	strcpy(arr[495]->name, "Snivy");
	strcpy(arr[495]->type, "Grass");
	strcpy(arr[496]->name, "Servine");
	strcpy(arr[496]->type, "Grass");
	strcpy(arr[497]->name, "Serperior");
	strcpy(arr[497]->type, "Grass");
	strcpy(arr[498]->name, "Tepig");
	strcpy(arr[498]->type, "Fire");
	strcpy(arr[499]->name, "Pignite");
	strcpy(arr[499]->type, "Fire Fighting");
	strcpy(arr[500]->name, "Emboar");
	strcpy(arr[500]->type, "Fire Fighting");
	strcpy(arr[501]->name, "Oshawott");
	strcpy(arr[501]->type, "Water");
	strcpy(arr[502]->name, "Dewott");
	strcpy(arr[502]->type, "Water");
	strcpy(arr[503]->name, "Samurott");
	strcpy(arr[503]->type, "Water");
	strcpy(arr[504]->name, "Patrat");
	strcpy(arr[504]->type, "Normal");
	strcpy(arr[505]->name, "Watchog");
	strcpy(arr[505]->type, "Normal");
	strcpy(arr[506]->name, "Lillipup");
	strcpy(arr[506]->type, "Normal");
	strcpy(arr[507]->name, "Herdier");
	strcpy(arr[507]->type, "Normal");
	strcpy(arr[508]->name, "Stoutland");
	strcpy(arr[508]->type, "Normal");
	strcpy(arr[509]->name, "Purrloin");
	strcpy(arr[509]->type, "Dark");
	strcpy(arr[510]->name, "Liepard");
	strcpy(arr[510]->type, "Dark");
	strcpy(arr[511]->name, "Pansage");
	strcpy(arr[511]->type, "Grass");
	strcpy(arr[512]->name, "Simisage");
	strcpy(arr[512]->type, "Grass");
	strcpy(arr[513]->name, "Pansear");
	strcpy(arr[513]->type, "Fire");
	strcpy(arr[514]->name, "Simisear");
	strcpy(arr[514]->type, "Fire");
	strcpy(arr[515]->name, "Panpour");
	strcpy(arr[515]->type, "Water");
	strcpy(arr[516]->name, "Simipour");
	strcpy(arr[516]->type, "Water");
	strcpy(arr[517]->name, "Munna");
	strcpy(arr[517]->type, "Psychic");
	strcpy(arr[518]->name, "Musharna");
	strcpy(arr[518]->type, "Psychic");
	strcpy(arr[519]->name, "Pidove");
	strcpy(arr[519]->type, "Normal Flying");
	strcpy(arr[520]->name, "Tranquill");
	strcpy(arr[520]->type, "Normal Flying");
	strcpy(arr[521]->name, "Unfezant");
	strcpy(arr[521]->type, "Normal Flying");
	strcpy(arr[522]->name, "Blitzle");
	strcpy(arr[522]->type, "Electric");
	strcpy(arr[523]->name, "Zebstrika");
	strcpy(arr[523]->type, "Electric");
	strcpy(arr[524]->name, "Roggenrola");
	strcpy(arr[524]->type, "Rock");
	strcpy(arr[525]->name, "Boldore");
	strcpy(arr[525]->type, "Rock");
	strcpy(arr[526]->name, "Gigalith");
	strcpy(arr[526]->type, "Rock");
	strcpy(arr[527]->name, "Woobat");
	strcpy(arr[527]->type, "Psychic Flying");
	strcpy(arr[528]->name, "Swoobat");
	strcpy(arr[528]->type, "Psychic Flying");
	strcpy(arr[529]->name, "Drilbur");
	strcpy(arr[529]->type, "Ground");
	strcpy(arr[530]->name, "Excadrill");
	strcpy(arr[530]->type, "Ground Steel");
	strcpy(arr[531]->name, "Audino");
	strcpy(arr[531]->type, "Normal");
	strcpy(arr[532]->name, "Timburr");
	strcpy(arr[532]->type, "Fighting");
	strcpy(arr[533]->name, "Gurdurr");
	strcpy(arr[533]->type, "Fighting");
	strcpy(arr[534]->name, "Conkeldurr");
	strcpy(arr[534]->type, "Fighting");
	strcpy(arr[535]->name, "Tympole");
	strcpy(arr[535]->type, "Water");
	strcpy(arr[536]->name, "Palpitoad");
	strcpy(arr[536]->type, "Water Ground");
	strcpy(arr[537]->name, "Seismitoad");
	strcpy(arr[537]->type, "Water Ground");
	strcpy(arr[538]->name, "Throh");
	strcpy(arr[538]->type, "Fighting");
	strcpy(arr[539]->name, "Sawk");
	strcpy(arr[539]->type, "Fighting");
	strcpy(arr[540]->name, "Sewaddle");
	strcpy(arr[540]->type, "Bug Grass");
	strcpy(arr[541]->name, "Swadloon");
	strcpy(arr[541]->type, "Bug Grass");
	strcpy(arr[542]->name, "Leavanny");
	strcpy(arr[542]->type, "Bug Grass");
	strcpy(arr[543]->name, "Venipede");
	strcpy(arr[543]->type, "Bug Poison");
	strcpy(arr[544]->name, "Whirlipede");
	strcpy(arr[544]->type, "Bug Poison");
	strcpy(arr[545]->name, "Scolipede");
	strcpy(arr[545]->type, "Bug Poison");
	strcpy(arr[546]->name, "Cottonee");
	strcpy(arr[546]->type, "Grass Fairy");
	strcpy(arr[547]->name, "Whimsicott");
	strcpy(arr[547]->type, "Grass Fairy");
	strcpy(arr[548]->name, "Petilil");
	strcpy(arr[548]->type, "Grass");
	strcpy(arr[549]->name, "Lilligant");
	strcpy(arr[549]->type, "Grass");
	strcpy(arr[550]->name, "Basculin");
	strcpy(arr[550]->type, "Water");
	strcpy(arr[551]->name, "Sandile");
	strcpy(arr[551]->type, "Ground Dark");
	strcpy(arr[552]->name, "Krokorok");
	strcpy(arr[552]->type, "Ground Dark");
	strcpy(arr[553]->name, "Krookodile");
	strcpy(arr[553]->type, "Ground Dark");
	strcpy(arr[554]->name, "Darumaka");
	strcpy(arr[554]->type, "Fire");
	strcpy(arr[555]->name, "Darmanitan");
	strcpy(arr[555]->type, "Fire");
	strcpy(arr[556]->name, "Maractus");
	strcpy(arr[556]->type, "Grass");
	strcpy(arr[557]->name, "Dwebble");
	strcpy(arr[557]->type, "Bug Rock");
	strcpy(arr[558]->name, "Crustle");
	strcpy(arr[558]->type, "Bug Rock");
	strcpy(arr[559]->name, "Scraggy");
	strcpy(arr[559]->type, "Dark Fighting");
	strcpy(arr[560]->name, "Scrafty");
	strcpy(arr[560]->type, "Dark Fighting");
	strcpy(arr[561]->name, "Sigilyph");
	strcpy(arr[561]->type, "Psychic Flying");
	strcpy(arr[562]->name, "Yamask");
	strcpy(arr[562]->type, "Ghost");
	strcpy(arr[563]->name, "Cofagrigus");
	strcpy(arr[563]->type, "Ghost");
	strcpy(arr[564]->name, "Tirtouga");
	strcpy(arr[564]->type, "Water Rock");
	strcpy(arr[565]->name, "Carracosta");
	strcpy(arr[565]->type, "Water Rock");
	strcpy(arr[566]->name, "Archen");
	strcpy(arr[566]->type, "Rock Flying");
	strcpy(arr[567]->name, "Archeops");
	strcpy(arr[567]->type, "Rock Flying");
	strcpy(arr[568]->name, "Trubbish");
	strcpy(arr[568]->type, "Poison");
	strcpy(arr[569]->name, "Garbodor");
	strcpy(arr[569]->type, "Poison");
	strcpy(arr[570]->name, "Zorua");
	strcpy(arr[570]->type, "Dark");
	strcpy(arr[571]->name, "Zoroark");
	strcpy(arr[571]->type, "Dark");
	strcpy(arr[572]->name, "Minccino");
	strcpy(arr[572]->type, "Normal");
	strcpy(arr[573]->name, "Cinccino");
	strcpy(arr[573]->type, "Normal");
	strcpy(arr[574]->name, "Gothita");
	strcpy(arr[574]->type, "Psychic");
	strcpy(arr[575]->name, "Gothorita");
	strcpy(arr[575]->type, "Psychic");
	strcpy(arr[576]->name, "Gothitelle");
	strcpy(arr[576]->type, "Psychic");
	strcpy(arr[577]->name, "Solosis");
	strcpy(arr[577]->type, "Psychic");
	strcpy(arr[578]->name, "Duosion");
	strcpy(arr[578]->type, "Psychic");
	strcpy(arr[579]->name, "Reuniclus");
	strcpy(arr[579]->type, "Psychic");
	strcpy(arr[580]->name, "Ducklett");
	strcpy(arr[580]->type, "Water Flying");
	strcpy(arr[581]->name, "Swanna");
	strcpy(arr[581]->type, "Water Flying");
	strcpy(arr[582]->name, "Vanillite");
	strcpy(arr[582]->type, "Ice");
	strcpy(arr[583]->name, "Vanillish");
	strcpy(arr[583]->type, "Ice");
	strcpy(arr[584]->name, "Vanilluxe");
	strcpy(arr[584]->type, "Ice");
	strcpy(arr[585]->name, "Deerling");
	strcpy(arr[585]->type, "Normal Grass");
	strcpy(arr[586]->name, "Sawsbuck");
	strcpy(arr[586]->type, "Normal Grass");
	strcpy(arr[587]->name, "Emolga");
	strcpy(arr[587]->type, "Electric Flying");
	strcpy(arr[588]->name, "Karrablast");
	strcpy(arr[588]->type, "Bug");
	strcpy(arr[589]->name, "Escavalier");
	strcpy(arr[589]->type, "Bug Steel");
	strcpy(arr[590]->name, "Foongus");
	strcpy(arr[590]->type, "Grass Poison");
	strcpy(arr[591]->name, "Amoonguss");
	strcpy(arr[591]->type, "Grass Poison");
	strcpy(arr[592]->name, "Frillish");
	strcpy(arr[592]->type, "Water Ghost");
	strcpy(arr[593]->name, "Jellicent");
	strcpy(arr[593]->type, "Water Ghost");
	strcpy(arr[594]->name, "Alomomola");
	strcpy(arr[594]->type, "Water");
	strcpy(arr[595]->name, "Joltik");
	strcpy(arr[595]->type, "Bug Electric");
	strcpy(arr[596]->name, "Galvantula");
	strcpy(arr[596]->type, "Bug Electric");
	strcpy(arr[597]->name, "Ferroseed");
	strcpy(arr[597]->type, "Grass Steel");
	strcpy(arr[598]->name, "Ferrothorn");
	strcpy(arr[598]->type, "Grass Steel");
	strcpy(arr[599]->name, "Klink");
	strcpy(arr[599]->type, "Steel");
	strcpy(arr[600]->name, "Klang");
	strcpy(arr[600]->type, "Steel");
	strcpy(arr[601]->name, "Klinklang");
	strcpy(arr[601]->type, "Steel");
	strcpy(arr[602]->name, "Tynamo");
	strcpy(arr[602]->type, "Electric");
	strcpy(arr[603]->name, "Eelektrik");
	strcpy(arr[603]->type, "Electric");
	strcpy(arr[604]->name, "Eelektross");
	strcpy(arr[604]->type, "Electric");
	strcpy(arr[605]->name, "Elgyem");
	strcpy(arr[605]->type, "Psychic");
	strcpy(arr[606]->name, "Beheeyem");
	strcpy(arr[606]->type, "Psychic");
	strcpy(arr[607]->name, "Litwick");
	strcpy(arr[607]->type, "Ghost Fire");
	strcpy(arr[608]->name, "Lampent");
	strcpy(arr[608]->type, "Ghost Fire");
	strcpy(arr[609]->name, "Chandelure");
	strcpy(arr[609]->type, "Ghost Fire");
	strcpy(arr[610]->name, "Axew");
	strcpy(arr[610]->type, "Dragon");
	strcpy(arr[611]->name, "Fraxure");
	strcpy(arr[611]->type, "Dragon");
	strcpy(arr[612]->name, "Haxorus");
	strcpy(arr[612]->type, "Dragon");
	strcpy(arr[613]->name, "Cubchoo");
	strcpy(arr[613]->type, "Ice");
	strcpy(arr[614]->name, "Beartic");
	strcpy(arr[614]->type, "Ice");
	strcpy(arr[615]->name, "Cryogonal");
	strcpy(arr[615]->type, "Ice");
	strcpy(arr[616]->name, "Shelmet");
	strcpy(arr[616]->type, "Bug");
	strcpy(arr[617]->name, "Accelgor");
	strcpy(arr[617]->type, "Bug");
	strcpy(arr[618]->name, "Stunfisk");
	strcpy(arr[618]->type, "Electric Ground");
	strcpy(arr[619]->name, "Mienfoo");
	strcpy(arr[619]->type, "Fighting");
	strcpy(arr[620]->name, "Mienshao");
	strcpy(arr[620]->type, "Fighting");
	strcpy(arr[621]->name, "Druddigon");
	strcpy(arr[621]->type, "Dragon");
	strcpy(arr[622]->name, "Golett");
	strcpy(arr[622]->type, "Ground Ghost");
	strcpy(arr[623]->name, "Golurk");
	strcpy(arr[623]->type, "Ground Ghost");
	strcpy(arr[624]->name, "Pawniard");
	strcpy(arr[624]->type, "Dark Steel");
	strcpy(arr[625]->name, "Bisharp");
	strcpy(arr[625]->type, "Dark Steel");
	strcpy(arr[626]->name, "Bouffalant");
	strcpy(arr[626]->type, "Normal");
	strcpy(arr[627]->name, "Rufflet");
	strcpy(arr[627]->type, "Normal Flying");
	strcpy(arr[628]->name, "Braviary");
	strcpy(arr[628]->type, "Normal Flying");
	strcpy(arr[629]->name, "Vullaby");
	strcpy(arr[629]->type, "Dark Flying");
	strcpy(arr[630]->name, "Mandibuzz");
	strcpy(arr[630]->type, "Dark Flying");
	strcpy(arr[631]->name, "Heatmor");
	strcpy(arr[631]->type, "Fire");
	strcpy(arr[632]->name, "Durant");
	strcpy(arr[632]->type, "Bug Steel");
	strcpy(arr[633]->name, "Deino");
	strcpy(arr[633]->type, "Dark Dragon");
	strcpy(arr[634]->name, "Zweilous");
	strcpy(arr[634]->type, "Dark Dragon");
	strcpy(arr[635]->name, "Hydreigon");
	strcpy(arr[635]->type, "Dark Dragon");
	strcpy(arr[636]->name, "Larvesta");
	strcpy(arr[636]->type, "Bug Fire");
	strcpy(arr[637]->name, "Volcarona");
	strcpy(arr[637]->type, "Bug Fire");
	strcpy(arr[638]->name, "Cobalion");
	strcpy(arr[638]->type, "Steel Fighting");
	strcpy(arr[639]->name, "Terrakion");
	strcpy(arr[639]->type, "Rock Fighting");
	strcpy(arr[640]->name, "Virizion");
	strcpy(arr[640]->type, "Grass Fighting");
	strcpy(arr[641]->name, "Tornadus");
	strcpy(arr[641]->type, "Flying");
	strcpy(arr[642]->name, "Thundurus");
	strcpy(arr[642]->type, "Electric Flying");
	strcpy(arr[643]->name, "Reshiram");
	strcpy(arr[643]->type, "Dragon Fire");
	strcpy(arr[644]->name, "Zekrom");
	strcpy(arr[644]->type, "Dragon Electric");
	strcpy(arr[645]->name, "Landorus");
	strcpy(arr[645]->type, "Ground Flying");
	strcpy(arr[646]->name, "Kyurem");
	strcpy(arr[646]->type, "Dragon Ice");
	strcpy(arr[647]->name, "Keldeo");
	strcpy(arr[647]->type, "Water Fighting");
	strcpy(arr[648]->name, "Meloetta");
	strcpy(arr[648]->type, "Normal Psychic");
	strcpy(arr[649]->name, "Genesect");
	strcpy(arr[649]->type, "Bug Steel");
	strcpy(arr[650]->name, "Chespin");
	strcpy(arr[650]->type, "Grass");
	strcpy(arr[651]->name, "Quilladin");
	strcpy(arr[651]->type, "Grass");
	strcpy(arr[652]->name, "Chesnaught");
	strcpy(arr[652]->type, "Grass Fighting");
	strcpy(arr[653]->name, "Fennekin");
	strcpy(arr[653]->type, "Fire");
	strcpy(arr[654]->name, "Braixen");
	strcpy(arr[654]->type, "Fire");
	strcpy(arr[655]->name, "Delphox");
	strcpy(arr[655]->type, "Fire Psychic");
	strcpy(arr[656]->name, "Froakie");
	strcpy(arr[656]->type, "Water");
	strcpy(arr[657]->name, "Frogadier");
	strcpy(arr[657]->type, "Water");
	strcpy(arr[658]->name, "Greninja");
	strcpy(arr[658]->type, "Water Dark");
	strcpy(arr[659]->name, "Bunnelby");
	strcpy(arr[659]->type, "Normal");
	strcpy(arr[660]->name, "Diggersby");
	strcpy(arr[660]->type, "Normal Ground");
	strcpy(arr[661]->name, "Fletchling");
	strcpy(arr[661]->type, "Normal Flying");
	strcpy(arr[662]->name, "Fletchinder");
	strcpy(arr[662]->type, "Fire Flying");
	strcpy(arr[663]->name, "Talonflame");
	strcpy(arr[663]->type, "Fire Flying");
	strcpy(arr[664]->name, "Scatterbug");
	strcpy(arr[664]->type, "Bug");
	strcpy(arr[665]->name, "Spewpa");
	strcpy(arr[665]->type, "Bug");
	strcpy(arr[666]->name, "Vivillon");
	strcpy(arr[666]->type, "Bug Flying");
	strcpy(arr[667]->name, "Litleo");
	strcpy(arr[667]->type, "Fire Normal");
	strcpy(arr[668]->name, "Pyroar");
	strcpy(arr[668]->type, "Fire Normal");
	strcpy(arr[669]->name, "Flabébé");
	strcpy(arr[669]->type, "Fairy");
	strcpy(arr[670]->name, "Floette");
	strcpy(arr[670]->type, "Fairy");
	strcpy(arr[671]->name, "Florges");
	strcpy(arr[671]->type, "Fairy");
	strcpy(arr[672]->name, "Skiddo");
	strcpy(arr[672]->type, "Grass");
	strcpy(arr[673]->name, "Gogoat");
	strcpy(arr[673]->type, "Grass");
	strcpy(arr[674]->name, "Pancham");
	strcpy(arr[674]->type, "Fighting");
	strcpy(arr[675]->name, "Pangoro");
	strcpy(arr[675]->type, "Fighting Dark");
	strcpy(arr[676]->name, "Furfrou");
	strcpy(arr[676]->type, "Normal");
	strcpy(arr[677]->name, "Espurr");
	strcpy(arr[677]->type, "Psychic");
	strcpy(arr[678]->name, "Meowstic");
	strcpy(arr[678]->type, "Psychic");
	strcpy(arr[679]->name, "Honedge");
	strcpy(arr[679]->type, "Steel Ghost");
	strcpy(arr[680]->name, "Doublade");
	strcpy(arr[680]->type, "Steel Ghost");
	strcpy(arr[681]->name, "Aegislash");
	strcpy(arr[681]->type, "Steel Ghost");
	strcpy(arr[682]->name, "Spritzee");
	strcpy(arr[682]->type, "Fairy");
	strcpy(arr[683]->name, "Aromatisse");
	strcpy(arr[683]->type, "Fairy");
	strcpy(arr[684]->name, "Swirlix");
	strcpy(arr[684]->type, "Fairy");
	strcpy(arr[685]->name, "Slurpuff");
	strcpy(arr[685]->type, "Fairy");
	strcpy(arr[686]->name, "Inkay");
	strcpy(arr[686]->type, "Dark Psychic");
	strcpy(arr[687]->name, "Malamar");
	strcpy(arr[687]->type, "Dark Psychic");
	strcpy(arr[688]->name, "Binacle");
	strcpy(arr[688]->type, "Rock Water");
	strcpy(arr[689]->name, "Barbaracle");
	strcpy(arr[689]->type, "Rock Water");
	strcpy(arr[690]->name, "Skrelp");
	strcpy(arr[690]->type, "Poison Water");
	strcpy(arr[691]->name, "Dragalge");
	strcpy(arr[691]->type, "Poison Dragon");
	strcpy(arr[692]->name, "Clauncher");
	strcpy(arr[692]->type, "Water");
	strcpy(arr[693]->name, "Clawitzer");
	strcpy(arr[693]->type, "Water");
	strcpy(arr[694]->name, "Helioptile");
	strcpy(arr[694]->type, "Electric Normal");
	strcpy(arr[695]->name, "Heliolisk");
	strcpy(arr[695]->type, "Electric Normal");
	strcpy(arr[696]->name, "Tyrunt");
	strcpy(arr[696]->type, "Rock Dragon");
	strcpy(arr[697]->name, "Tyrantrum");
	strcpy(arr[697]->type, "Rock Dragon");
	strcpy(arr[698]->name, "Amaura");
	strcpy(arr[698]->type, "Rock Ice");
	strcpy(arr[699]->name, "Aurorus");
	strcpy(arr[699]->type, "Rock Ice");
	strcpy(arr[700]->name, "Sylveon");
	strcpy(arr[700]->type, "Fairy");
	strcpy(arr[701]->name, "Hawlucha");
	strcpy(arr[701]->type, "Fighting Flying");
	strcpy(arr[702]->name, "Dedenne");
	strcpy(arr[702]->type, "Electric Fairy");
	strcpy(arr[703]->name, "Carbink");
	strcpy(arr[703]->type, "Rock Fairy");
	strcpy(arr[704]->name, "Goomy");
	strcpy(arr[704]->type, "Dragon");
	strcpy(arr[705]->name, "Sliggoo");
	strcpy(arr[705]->type, "Dragon");
	strcpy(arr[706]->name, "Goodra");
	strcpy(arr[706]->type, "Dragon");
	strcpy(arr[707]->name, "Klefki");
	strcpy(arr[707]->type, "Steel Fairy");
	strcpy(arr[708]->name, "Phantump");
	strcpy(arr[708]->type, "Ghost Grass");
	strcpy(arr[709]->name, "Trevenant");
	strcpy(arr[709]->type, "Ghost Grass");
	strcpy(arr[710]->name, "Pumpkaboo");
	strcpy(arr[710]->type, "Ghost Grass");
	strcpy(arr[711]->name, "Gourgeist");
	strcpy(arr[711]->type, "Ghost Grass");
	strcpy(arr[712]->name, "Bergmite");
	strcpy(arr[712]->type, "Ice");
	strcpy(arr[713]->name, "Avalugg");
	strcpy(arr[713]->type, "Ice");
	strcpy(arr[714]->name, "Noibat");
	strcpy(arr[714]->type, "Flying Dragon");
	strcpy(arr[715]->name, "Noivern");
	strcpy(arr[715]->type, "Flying Dragon");
	strcpy(arr[716]->name, "Xerneas");
	strcpy(arr[716]->type, "Fairy");
	strcpy(arr[717]->name, "Yveltal");
	strcpy(arr[717]->type, "Dark Flying");
	strcpy(arr[718]->name, "Zygarde");
	strcpy(arr[718]->type, "Dragon Ground");
	return;
}